server:
    port: 8089

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/ead-notification
    username: postgres
    password: notification_123
  jpa:
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: 'http://localhost:8761/eureka'
    instance:
        hostname: localhost