server:
    port: 8087

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/ead-authuser
        username: postgres
        password: authuser_123
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
            
