server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5433/ead-course
    username: postgres
    password: course_123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  output:
    ansi:
      enabled: Always


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
    client:
        serviceUrl:
            defaultZone: 'http://localhost:8761/eureka'
    instance:
        hostname: localhost