server:
    port: 8088

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5433/ead-course
        username: postgres
        password: course_123
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true